#!/usr/bin/env python3
"""narration/<set>.json -> js/narration-<set>.js

The JSON is the single source of truth for every sentence the site speaks or
prints.  This step embeds it as a plain script (no fetch), so the site also
works when opened directly from disk (file://), and records the duration of
each audio clip that has already been generated, so the player can show a
running time before the clip is loaded.
"""
import argparse, json, pathlib, subprocess, shutil

SITE = pathlib.Path(__file__).resolve().parents[1]
ap = argparse.ArgumentParser(); ap.add_argument("--set", choices=["technical", "explainer"], default="technical"); args = ap.parse_args()
SCRIPT = SITE / f"narration/{args.set}.json"; OUT = SITE / f"js/narration-{args.set}.js"; AUDIO = SITE / "audio" / args.set

def duration(path):
    if not path.exists() or shutil.which("ffprobe") is None:
        return None
    try:
        out = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                              "-of", "csv=p=0", str(path)], capture_output=True, text=True,
                             timeout=20).stdout.strip()
        return round(float(out), 2)
    except (ValueError, subprocess.SubprocessError):
        return None

data = json.loads(SCRIPT.read_text())
for ch in data["chapters"]:
    for b in ch["beats"]:
        b["dur"] = {}
        for lang in ("en", "zh"):
            d = duration(AUDIO / lang / f"{ch['id']}-{b['id']}.m4a")
            if d is not None:
                b["dur"][lang] = d
OUT.write_text(f"// Generated by tools/build_narration.py from narration/{args.set}.json -- do not edit.\n"
               "window.CPV_NARRATION = " + json.dumps(data, ensure_ascii=False, indent=1) + ";\n")
n = sum(len(c["beats"]) for c in data["chapters"])
tot = {lang: round(sum(b["dur"].get(lang, 0) for c in data["chapters"] for b in c["beats"]), 1)
       for lang in ("en", "zh")}
print(f"wrote {OUT.name}: {len(data['chapters'])} chapters, {n} beats, audio seconds {tot}")
