#!/usr/bin/env python3
"""Bundle the site into one self-contained HTML file (scripts, CSS and narration
audio inlined as data URIs).  The result can be e-mailed, attached to a
submission, or published anywhere that accepts a single page.

    python3 tools/build_single.py                 # dist/cpv-explainer.html, English audio only
    python3 tools/build_single.py --lang en,zh    # both narrations (about twice the size)
    python3 tools/build_single.py --no-audio      # text + browser speech synthesis only

Google Fonts are still linked (they need the network); everything else is local.
"""
import argparse, base64, pathlib, re

SITE = pathlib.Path(__file__).resolve().parents[1]
ap = argparse.ArgumentParser()
ap.add_argument("--page", choices=["technical", "explainer"], default="technical")
ap.add_argument("--lang", default="en")
ap.add_argument("--no-audio", action="store_true")
ap.add_argument("--out", default=None)
args = ap.parse_args()

PAGE = SITE / args.page / "index.html"
html = PAGE.read_text()
if args.out is None:
    args.out = str(SITE / f"dist/cpv-{args.page}.html")

# CSS
css = (SITE / "css/site.css").read_text()
html = html.replace('<link rel="stylesheet" href="../css/site.css">', "<style>\n" + css + "\n</style>")

# scripts, in order
def inline_script(m):
    src = m.group(1)
    return "<script>\n" + (PAGE.parent / src).resolve().read_text() + "\n</script>"
html = re.sub(r'<script src="([^"]+)"></script>', inline_script, html)

# audio map
if not args.no_audio:
    langs = [l.strip() for l in args.lang.split(",") if l.strip()]
    entries = []
    for lang in langs:
        d = SITE / "audio" / args.page / lang
        if not d.exists():
            continue
        items = []
        for f in sorted(d.glob("*.m4a")):
            b64 = base64.b64encode(f.read_bytes()).decode("ascii")
            items.append(f'"{f.stem}": "data:audio/mp4;base64,{b64}"')
        entries.append(f'"{lang}": {{' + ",\n".join(items) + "}")
    audio_js = "<script>window.CPV_AUDIO = {" + ",\n".join(entries) + "};</script>"
    html = html.replace("<script>\n// Generated by tools/build_narration.py", audio_js + "\n<script>\n// Generated by tools/build_narration.py", 1)

# the PDF link cannot be bundled; point at the file next to the page if present
html = html.replace('href="../paper/main.pdf"', 'href="main.pdf"').replace('href="../"', 'href="https://example.org/"')

out = pathlib.Path(args.out); out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(html)
print(f"wrote {out} ({out.stat().st_size / 1e6:.1f} MB)")
